Do not call strtolower on null (PHP 8.1 warning)
oleg-andreyev/MinkPhpWebDriver pull request #76
Opened 2022-10-25 20:58 UTC by marinaglancy

"option" and "select" elements return null as their element type and it causes a notice in PHP 8.1:

    8192: strtolower(): Passing null to parameter #1 () of type string is deprecated in /var/www/html/vendor/oleg-andreyev/mink-phpwebdriver/src/WebDriver.php line 578

2022-10-26 11:23 UTC, andrewnicols approved these changes

2022-10-26 11:24 UTC, andrewnicols commented
@oleg-andreyev, any chance we can land this. We're trying to get compatibility with PHP 8.1 ASAP and this is a blocker for us.

2022-10-29 14:50 UTC, oleg-andreyev commented
> @oleg-andreyev, any chance we can land this. We're trying to get compatibility with PHP 8.1 ASAP and this is a blocker for us.

One thing that bugs me, input has missing or unknown "type" it should fallback "text"

MDN:
> If omitted (or an unknown value is specified), the input type text is used, creating a plaintext input field.

2022-10-29 14:53 UTC, oleg-andreyev requested changes

2022-10-29 14:53 UTC, oleg-andreyev commented on src/WebDriver.php
> +        $elementType = strtolower($element->getAttribute('type') ?? '');
Let's add fallback to "text" and please search for other places (line 650)

2022-10-29 20:48 UTC, oleg-andreyev commented on src/WebDriver.php
> +        $elementType = strtolower($element->getAttribute('type') ?? '');
better to update "\OAndreyev\Mink\Driver\WebDriver::getAttribute":
if $element->getTagName() === input and $element->getAttribute('type') === null, return text as default and fallback

2022-10-29 20:55 UTC, oleg-andreyev commented
also I've done some work on https://github.com/oleg-andreyev/MinkPhpWebDriver/releases/tag/v1.2.0

now PHP >= 7.4 and build is working.

2022-11-07 15:52 UTC, marinaglancy commented
FYI In minkphp/MinkSelenium2Driver it is added as `?? ''` in four different places but the other three are only engaged if `type='input'`
https://github.com/minkphp/MinkSelenium2Driver/commit/96ba5d71393e198f6ea2f6a61b1c5d14659757fc

2022-11-09 22:25 UTC, oleg-andreyev approved these changes

2022-11-21 15:35 UTC, merged

2022-11-22 11:40 UTC, stronk7 commented
Hi @oleg-andreyev ,

any reason the new release is not showing @ packagist? https://packagist.org/packages/oleg-andreyev/mink-phpwebdriver

Was just trying to update our repos here to use it and composer cannot find it, so far.

Ciao :-)

2022-11-22 21:02 UTC, oleg-andreyev commented
@stronk7 fixed.

It appears I made a typo in tag/release
![image](https://user-images.githubusercontent.com/1244112/203420519-61709276-d5c9-49ae-9293-07cedc1195df.png)

tag is updated https://packagist.org/packages/oleg-andreyev/mink-phpwebdriver#v1.2.1

2022-11-22 22:16 UTC, stronk7 commented
Aha, great! Heap thanks!